server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/profile/**

