
spring:
  application:
    name: 'socket-service'

server:
  port: 8088

# Registering application in Eureka Server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8085/v1/auth